version: "3.8"

volumes:
  traefik_letsencrypt:
    driver: local
    name: traefik_letsencrypt

services:
  traefik:
    container_name: traefik
    image: traefik:v3.1.5
    network_mode: host
    healthcheck:
      test: [ "CMD-SHELL", "traefik healthcheck || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    environment:
      - CF_API_EMAIL=$CF_API_EMAIL
      - CF_API_KEY=$CF_API_KEY
      - PRIVATE_IP=$PRIVATE_IP
    volumes:
      - type: volume
        source: traefik_letsencrypt
        target: /letsencrypt
      - type: bind
        source: ./config
        target: /etc/traefik
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock