http:
  routers:
    dashboard:
      service: api@internal
      rule: Host(`pi.home.sidevision.io`) && PathPrefix(`/api`, `/dashboard`)
      entrypoints: websecure
      tls:
        certResolver: cloudflare

    metrics:
      service: prometheus@internal
      rule: Host(`pi.home.sidevision.io`) && Path(`/traefik/metrics`)
      entrypoints: websecure
      tls:
        certResolver: cloudflare

    node-exporter:
      service: node-exporter
      rule: Host(`pi.home.sidevision.io`) && Path(`/metrics`)
      entrypoints: websecure
      tls:
        certResolver: cloudflare

    bind9-exporter:
      service: bind9-exporter
      rule: Host(`dns.home.sidevision.io`) && Path(`/metrics`)
      entrypoints: websecure
      tls:
        certResolver: cloudflare
    
    home-assistant:
      service: home-assistant
      rule: Host(`home.sidevision.io`)
      entrypoints:
        - websecure
        - web
      tls:
        certResolver: cloudflare