http:
  routers:
    dashboard:
      service: api@internal
      rule: Host(`zimaboard.home.sidevision.io`) && PathPrefix(`/api`, `/dashboard`)
      entrypoints: websecure
      tls:
        certResolver: cloudflare

    metrics:
      service: prometheus@internal
      rule: Host(`zimaboard.home.sidevision.io`) && Path(`/traefik/metrics`)
      entrypoints: websecure
      tls:
        certResolver: cloudflare

    node-exporter:
      service: node-exporter
      rule: Host(`zimaboard.home.sidevision.io`) && Path(`/metrics`)
      entrypoints: websecure
      tls:
        certResolver: cloudflare

    casaos:
      service: casaos
      rule: Host(`casaos.home.sidevision.io`)
      entrypoints: websecure
      tls:
        certResolver: cloudflare

    z2m:
      service: z2m
      rule: Host(`z2m.home.sidevision.io`)
      entrypoints: websecure
      tls:
        certResolver: cloudflare

