http:
  services:
    node-exporter:
      loadBalancer:
        servers:
          - url: http://localhost:9100/metrics
    casaos:
      loadBalancer:
        servers:
          - url: http://localhost:8000
    z2m:
      loadBalancer:
        servers:
          - url: http://localhost:8081
