http:
  services:
    node-exporter:
      loadBalancer:
        servers:
          - url: http://{{ env "PRIVATE_IP" }}:9100/metrics
    casaos:
      loadBalancer:
        servers:
          - url: http://{{ env "PRIVATE_IP" }}:8000
    home-assistant:
      loadBalancer:
        servers:
          - url: http://{{ env "PRIVATE_IP" }}:8123
